name: 'tokyo_weather'
version: '1.0.0'
config-version: 2

profile: 'tokyo_weather'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"