version: 2

models:
  - name: stg_temperature
    columns:
      - name: observed_at
        data_tests:
          - not_null
          - unique
      - name: temperature_c
        data_tests:
          - not_null